---
title       : MPG Tool Pitch
subtitle    : Presenting a valuable tool for car selection
author      : Mats Z
job         : Coursera Class Mate
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Are you tired of poor milage?  
  
  
  
* Today it is costly to use the car the way you're used to
* As gas prices are increasing, you should look at more economical solutions!  
* There are lots of available cars - but  
  
## - *HOW DO YOU SELECT?*

--- 
## An easy-to-use solution is what you need!                        
   
                              
   
* The most important aspect when it comes to get good milage on your car, is to select a car with reasonable horsepower capacity. 
* This is not an easy decision - how can you tell the milage just from the engine power level?
* And can you trust the milage figures from the car dealer?
  
   
## *You need a reliable tool to show you how milage depends on engine capacity!*

---

## Here's how it works  
  
Advanced mathematic algorithms and deep scientific research have come up with the following chart, showing the relation between engine power and milage:

```{r, echo = FALSE}
  data(mtcars)
  plot(mtcars$hp, mtcars$mpg, pch = 20, main = "MPG for different HP", xlab = "HP", ylab = "MPG", col = mtcars$cyl)
  legend("topright", legend = c("4 cylinders", "6 cylinders", "8 cylinders"), pch = 20, col = c(4, 6, 8), )
  abline(lm(mpg ~ hp, data = mtcars), col = "red")
```


--- 
## Now, get your own copy!                     
                              
                              
* Fortunately, we have the perfect tool for you to help you select the car model that fits your dreams and wallet!
* This amazing tool is provided *FREE OF CHARGE* - just click on the link and follow the directions.
  
[MPG Tool](https://matsz.shinyapps.io/DevelopingDataProducts_MatsZ/)
  
* Good luck in your car purchase planning!

